### ISSUE TITLE
无法查询

### ISSUE THREAD

**Issue by liuqianpan2008** [azmiao/github_reminder#2]
![image](https://user-images.githubusercontent.com/80571808/133921974-c95adfd1-f8db-4b87-9ef0-30aa6b7ac723.png)
![image](https://user-images.githubusercontent.com/80571808/133921977-e1981ace-5251-4bda-8cb3-77a87395a0ba.png)

**Comment by azmiao** [comment]
额，链接超时，只能说你的服务器偶尔连不上github，你可以试试用镜像站，github本身的cdn并不稳，国内偶尔连不上是正常现象，114的dns对部分地区会有一定帮助

**Comment by azmiao** [comment]
如换镜像站或使用代理仍然遇到问题，请后续反馈，这个issue先关闭了

**Comment by liuqianpan2008** [comment]
![image](https://user-images.githubusercontent.com/80571808/133965995-0f1300c0-7e81-46b1-a3a0-019278e1d091.png)
镜像站可以访问
![image](https://user-images.githubusercontent.com/80571808/133966021-691d83c8-3b0d-4581-8113-e8bbe32ed0f1.png)
![QQ截图20210920150003](https://user-images.githubusercontent.com/80571808/133966125-1fb69568-e983-4dbb-8c73-a478aa5841fe.png)

**Comment by azmiao** [comment]
> ![image](https://user-images.githubusercontent.com/80571808/133965995-0f1300c0-7e81-46b1-a3a0-019278e1d091.png)
> 镜像站可以访问
> ![image](https://user-images.githubusercontent.com/80571808/133966021-691d83c8-3b0d-4581-8113-e8bbe32ed0f1.png)
> ![QQ截图20210920150003](https://user-images.githubusercontent.com/80571808/133966125-1fb69568-e983-4dbb-8c73-a478aa5841fe.png)

啊这，你得试试你服务器能不能访问，你本地测试也没有用啊23333，我这边测试还是正常的

**Comment by liuqianpan2008** [comment]
![image](https://user-images.githubusercontent.com/80571808/133966652-305b84ee-87af-49ad-a715-7406ecf3aa01.png)

**Comment by azmiao** [comment]
额，怪了，我这还是没问题，你要不试试地河的镜像：github.dihe.moe

**Comment by azmiao** [comment]
你使用的那个镜像站在我这直接被防火墙拦下来了，直接被禁止访问了23333
