### ISSUE TITLE
发啥命令都没有反应

### ISSUE THREAD

**Issue by WindStill** [azmiao/github_reminder#4]
config/_ _bot_ _.py已经加了，也没有任何报错，发命令没有回应

**Comment by azmiao** [comment]
![-553f3d922429c846](https://user-images.githubusercontent.com/54100327/140677945-e6519973-1193-4499-8193-ef1a4b19d4c2.jpg)

**Comment by WindStill** [comment]
原来是缺少yaml依赖

**Comment by azmiao** [comment]
能解决就好，你光说一句没反应我啥也没法帮你

**Comment by WindStill** [comment]
> 能解决就好，你光说一句没反应我啥也没法帮你

少看了个日志，容器的日志没显示错误，Hoshino/log/error.log里面看到了。

建议加到readme里面。依赖：pyyaml

**Comment by azmiao** [comment]
好嘞，马上就加。我都快忘了这个依赖了23333
