### ISSUE TITLE
监控repo下分支节点时会返回未知错误！监控失败！

### ISSUE THREAD

**Issue by BlueDeer233** [azmiao/github_reminder#7]
例如：https://github.com/cc004/pcrjjc2/tree/notice-all
他的commit地址应该是：https://github.com/cc004/pcrjjc2/commits/notice-all
而不是：https://github.com/cc004/pcrjjc2/tree/notice-all/commits

**Comment by azmiao** [comment]
还有这种操作2333

**Comment by azmiao** [comment]
这个一会我去加个正则匹配一下吧
