### ISSUE TITLE
仓库更新消息会被推送两次

### ISSUE THREAD

**Issue by xulai1001** [azmiao/github_reminder#8]
RT
同一次更新消息，会间隔5分钟重复推送两次，原因不明？
![QQ截图20220707211841](https://user-images.githubusercontent.com/2126803/177784300-1e7d7182-615d-4d10-b4dd-e2b2c39b8bde.jpg)

**Comment by azmiao** [comment]
是正常的，已知BUG，看一直没人反馈就懒得修了2333，明天找时间改改吧（

**Comment by azmiao** [comment]
坏了，之前我也遇到了，现在还原不出来了2333

**Comment by azmiao** [comment]
能否给个推送的消息截图，我想看看是那种类型的commits，我现在测试测不出来了2333

**Comment by xulai1001** [comment]
![QQ图片20220708192332](https://user-images.githubusercontent.com/2126803/177983236-8e4ccec4-be34-42b2-915a-ccda46fa833e.png)
如图（刚好是对应上面截图的）
就是普通commit

**Comment by azmiao** [comment]
> ![QQ图片20220708192332](https://user-images.githubusercontent.com/2126803/177983236-8e4ccec4-be34-42b2-915a-ccda46fa833e.png) 如图（刚好是对应上面截图的） 就是普通commit

感谢，但是貌似我还是没有复现出来，奇怪了，我之前也遇到过有时候推送两次的问题，但是刚才测试又没测出来

**Comment by azmiao** [comment]
我再研究研究吧

**Comment by azmiao** [comment]
删了原来的垃圾代码重新写了一份，可以试试现在还有没有这样的问题23333（
[这个commit](https://github.com/azmiao/github_reminder/commit/e54368809c5f34c83fde9c6d1b75750384c9922e)

**Comment by xulai1001** [comment]
好的 谢谢dalao了明天测试一下

**Comment by xulai1001** [comment]
get_com.py第35行，获取名字的方式可能需要对不同环境下抓取到的页面进行分类处理
 'author': block.find('a', {"class": "commit-author user-mention"}).text,

网慢的时候（没有完全加载？）抓取到的网页内容为 <span class='commit-author user-mention' ...而不是a
（正常显示头像和人名时抓取到的是<a class=‘commit-author user-mention’）


具体报错为：

`库兰（R.sky） 17:27:40
查仓库 https://github.com/xulai1001/akgacha

库兰兰 bot 17:27:50
仓库https://github.com/xulai1001/akgacha最近5次commit如下：
▲2022-07-07 20:35:42 xulai1001提交了 "fix issue 7, add doroth gacha"
▲2022-07-04 00:08:22 xulai1001提交了 "July 3 修正读取限定池失败的问题。改进抽卡画面使用半身图展示结果，需要更新方舟资源"
▲2022-07-02 19:07:10 xulai1001提交了 "July 2 fix hoshino version"
▲2022-06-27 17:42:51 xulai1001提交了 "June 27 改回原本消息发送方式，优化蹲饼逻辑，修复游戏公告被风控的问题"
▲2022-06-27 15:48:47 **error**提交了 "Merge pull request #2 from AkatsukiYamisora/master"
`

**Comment by azmiao** [comment]
> commit-author user-mention

确实欸，感谢提醒，这就改一下

**Comment by azmiao** [comment]
百度说这可能是本地.gitconfig用户设置有问题或者身份验证问题，导致github识别不到

**Comment by xulai1001** [comment]
现在没问题了。
dalao的马娘插件也好用！感谢dalao

**Comment by azmiao** [comment]
好耶，可以摸鱼了2333！
